#Db connection =http://localhost:8088/h2-console/
spring:
  application:
    name: redis-login
  info:
    build:
      creator: Metehan Gultekin
  datasource:
    url: jdbc:postgresql://localhost:5432/redis_login
    username: postgres
    password: toor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8088